# Generated by Django 2.2.28 on 2022-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221104_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe', verbose_name='Картинка'),
        ),
    ]
